### ISSUE TITLE
Incorrect handling of readonly fields in object initializers

### ISSUE THREAD

**Issue by DeadMG** [ljw1004/csharpspec#7]
The way the specification defines object initializers is incorrect. Specifically, it lowers all initializers into property sets, when this is not always accurate. Fundamentally, object initializers should _initialize_. The fact that sometimes this may involve assignment should be an implementation detail. The main area where this distinction produces surprising behaviour is in the case of readonly fields. Consider the following program:

``` csharp
using System;
public class Test
{
    public readonly int num;
}

public class Program
{
    public static void Main()
    {
        var test = new Test { num = 1 };
    }
}
```

This produces the error that you can't assign to the field outside a variable initializer or constructor because it's readonly, despite the fact that the assignment clearly occurs inside an initializer.

The main issue I see with fixing this is interaction with legacy code, e.g. if Test had a meaningful default constructor that set the field. Previously this would have been a fixed value but now callers of Test can mutate it.

Therefore I'd suggest that, strictly in the case where the class declaring the property or field has no user-defined default constructor, and the object initializer does not call a custom constructor, and if a property the property has no user-defined setter, and the field or property is accessible for reading, then the assignment should be permitted.

**Comment by ljw1004** [comment]
@DeadMG I agree it's frustrating that you can't use object-initializers for readonly properties. We've discussed this matter in the past in C# language design meetings.

However... this repository is only for a markdown copy of the C# spec. For language design, feature requests/proposals, bug reports, please file them at https://github.com/dotnet/roslyn

Thanks!
